##ilebeat-6.2.3
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
  fields:
    log_source: 31-system
  tags: 31-system-log
- type: log
  enabled: true
  paths:
    - /data/logs/*.log
  fields:
    log_source: 31-nginx
  tags: 31-nginx-log
  include_lines: ['^ERR', '^WARN', 'ERR', 'WARN', 'error', '404', '504']
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
setup.template.settings:
  index.number_of_shards: 3
name: hkstaging31
setup.kibana:
  host: "kib1.XX.cn:5601"
output.logstash:
  hosts: ["lgh1.XX:5044"]
logging.level: error
